# Generated by Django 4.1.4 on 2022-12-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='options',
            options={'ordering': ['option'], 'verbose_name': 'Опис', 'verbose_name_plural': 'Опис'},
        ),
    ]
