# Generated by Django 4.1.4 on 2022-12-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_options_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='option',
            field=models.CharField(max_length=30),
        ),
    ]
