# Generated by Django 4.1.4 on 2022-12-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_alter_options_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='options',
        ),
        migrations.AddField(
            model_name='services',
            name='options',
            field=models.ManyToManyField(to='Services.options'),
        ),
    ]
