# Generated by Django 4.1.4 on 2022-12-23 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=15, verbose_name='Назва скілу')),
                ('skill_cat', models.CharField(max_length=20, verbose_name='Категорія скілу')),
                ('icon_svg', models.FileField(upload_to='skill_icons', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])])),
            ],
            options={
                'verbose_name': 'Навичка',
                'verbose_name_plural': 'Навички',
            },
        ),
    ]
