# Generated by Django 4.0 on 2022-06-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id'], 'verbose_name': 'Питання', 'verbose_name_plural': 'Питання'},
        ),
        migrations.AddField(
            model_name='question',
            name='publish_or_not',
            field=models.BooleanField(default=False, help_text='З галочкою - так, без - ні', verbose_name='Публікувати'),
        ),
    ]
