# Generated by Django 4.0 on 2022-06-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_alter_question_options_question_publish_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(verbose_name='Відповідь'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=120, verbose_name='Питання'),
        ),
    ]
