# Generated by Django 4.0 on 2022-06-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_option', models.CharField(max_length=40, verbose_name='Назва послуги')),
                ('price_of_option', models.CharField(max_length=20, verbose_name='Вартість')),
                ('publish_or_not', models.BooleanField(default=False, help_text='З галочкою - так, без - ні', verbose_name='Публікувати')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['id'],
            },
        ),
    ]
