# Generated by Django 4.0 on 2022-06-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Options', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='Publish',
            new_name='Можна публікувати',
        ),
    ]
