# Generated by Django 4.0 on 2022-06-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Options', '0002_rename_publish_option_можна публікувати'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='Можна публікувати',
        ),
        migrations.AddField(
            model_name='option',
            name='publish_or_not',
            field=models.BooleanField(default=False, help_text='Можна публікувати'),
        ),
    ]
