# Generated by Django 4.0 on 2022-06-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Options', '0004_alter_option_price_of_option_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Послуга', 'verbose_name_plural': 'Послуги'},
        ),
    ]
