# Generated by Django 4.0 on 2022-06-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Options', '0005_alter_option_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['id'], 'verbose_name': 'Послуга', 'verbose_name_plural': 'Послуги'},
        ),
        migrations.AlterField(
            model_name='option',
            name='name_of_option',
            field=models.CharField(max_length=40, verbose_name='Назва послуги'),
        ),
        migrations.AlterField(
            model_name='option',
            name='price_of_option',
            field=models.CharField(max_length=20, verbose_name='Вартість'),
        ),
    ]
