# Generated by Django 4.1.4 on 2022-12-22 06:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_site', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Тип проекту',
                'verbose_name_plural': 'Типи проекту',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_name', models.CharField(max_length=30, verbose_name='Назва сайту')),
                ('description', models.TextField(max_length=200, verbose_name='Опис сайту')),
                ('site_type', models.OneToOneField(default='Landing page', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Portfolio.typeofsite')),
                ('image', models.ImageField(upload_to='images', verbose_name='Фото сайту')),
                ('icon_svg', models.FileField(upload_to='site_icons', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])])),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекти',
            },
        ),
    ]
