# Generated by Django 4.1.4 on 2022-12-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofsite',
            name='type_of_site',
            field=models.CharField(max_length=30, verbose_name='Тип сайту'),
        ),
    ]
