# Generated by Django 4.0 on 2022-08-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_option', models.CharField(max_length=50, verbose_name='Назва послуги')),
                ('image', models.ImageField(upload_to='images', verbose_name='Фото послуги')),
                ('description', models.CharField(max_length=200, verbose_name='')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
            },
        ),
    ]
