# Generated by Django 4.0 on 2022-06-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_sertificate', models.CharField(max_length=50, verbose_name='Назва сертифікату')),
                ('image', models.ImageField(upload_to='images', verbose_name='Фото')),
                ('publish_or_not', models.BooleanField(default=False, help_text='З галочкою - так, без - ні', verbose_name='Публікувати')),
            ],
            options={
                'verbose_name': 'Сертифікат',
                'verbose_name_plural': 'Сертифікати',
            },
        ),
    ]
