# Generated by Django 4.0 on 2022-06-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rewiev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, verbose_name="Ім'я та фамілія")),
                ('user_phone', models.CharField(max_length=30, verbose_name='Телефон клієнта')),
                ('user_type', models.CharField(choices=[('Пацієнт(ка)', 'Пацієнт(ка)'), ('Знайомий(а)', 'Знайомий(а)')], default='Пацієнт(ка)', max_length=15, verbose_name='Тип клієнта')),
                ('rewiev_text', models.TextField(max_length=150, verbose_name='Текст відгуку')),
                ('publish_or_not', models.BooleanField(default=False, help_text='З галочкою - так, без - ні', verbose_name='Публікувати')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
    ]
