# Generated by Django 4.0 on 2022-06-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rewievs', '0002_alter_rewiev_options_alter_rewiev_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewiev',
            old_name='publist_or_not',
            new_name='publish_or_not',
        ),
    ]
