# Generated by Django 4.0 on 2022-06-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewievs', '0003_rename_publist_or_not_rewiev_publish_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewiev',
            name='rewiev_text',
            field=models.TextField(max_length=150, verbose_name='Текст відгуку'),
        ),
        migrations.AlterField(
            model_name='rewiev',
            name='user_type',
            field=models.CharField(choices=[('Пацієнт(ка)', 'Пацієнт(ка)'), ('Знайомий(а)', 'Знайомий(а)')], default='Пацієнт(ка)', max_length=15, verbose_name='Тип клієнта'),
        ),
        migrations.AlterField(
            model_name='rewiev',
            name='username',
            field=models.CharField(max_length=25, verbose_name="Ім'я та фамілія"),
        ),
    ]
